### ISSUE TITLE
specify .env variables with rush-init-project-plugin

### ISSUE THREAD

**Issue by vorobievik** [bytemate/rush-plugins#70]
Hi all!
I am new to rush and custom plugins.
I am trying to use rush-init-project-plugin in my monorepo
Is there any mechanism for generating a new project with auto-completion of the variables used in the project? Let me explain:

I have a create-react-app application template.
When using the template, I want to specify the port for the dev server and
cypress, specify the names and values ​​of other environment variables, create some  specific files,
specify the package name in package.json and more. 
is it possible? 
could you share some example?

**Comment by chengcyber** [comment]
Every template file will be rendered through [handlebars](https://handlebarsjs.com/guide/). So you need to add a new prompt to this plugin by specifying "prompts" property like

**<template_folder>/init.config.ts**

```ts
const config = {
  prompts: [
    // prompt here is a question object of inquirer.js https://www.npmjs.com/package/inquirer
  ]
}

export default config;
```

After user answering the question, the data will be used to render the source code. such as package name in package.json

**package.json**

```json
{
  "name": "{{ packageName }}",
}
```

The `packageName` prompt is predefined as one of the default prompts.

**Comment by vorobievik** [comment]
@chengcyber  thank you so much!!! that helped me

Now I want to go through the .env files in my monorepository to check that the port to run locally that I entered through the custom prompt is free.
 As I understand it, the IPlugin limits webpack/tapable functionality and I can't do this through the custom IPlugin plugin?
